version: '3'

services:
  app:
    container_name: back-nlw-return
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3333
    ports:
      - 3333:3333